version: "3"
services:
  web:
    build: .
    environment:
      - NODE_ENV=development
      - MYSQL_ADDR=mysql://sails:sails@database/sails_mysql
      - REDIS_URL=redis://redis:6379
      - S3_KEY=AKIA42L6K2HGDIY2ESVZ
      - S3_SECRET=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
      - S3_BUCKET=resizer-tp
      - S3_FOLDER=bigaston
    ports:
      - 1337:1337
    command: npm run dev
    volumes:
      - ./:/app
  database:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=sails_mysql
      - MYSQL_USER=sails
      - MYSQL_PASSWORD=sails
      - MYSQL_ROOT_PASSWORD=sails
  redis:
    image: redis